export const PRODUCT_ERROR = 'PRODUCT_ERROR'
export const PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST'

export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS'
export const GET_PRODUCT_BY_ID_SUCCESS = 'GET_PRODUCT_BY_ID_SUCCESS'
export const GET_PRODUCTS_BY_CATEGORY_ID = 'GET_PRODUCTS_BY_CATEGORY_ID'
export const GET_PRODUCTS_BY_CATEGORY_NAME = 'GET_PRODUCTS_BY_CATEGORY_NAME'

export const GET_PRODUCT_BY_ZONE_SUCCESS = 'GET_PRODUCT_BY_ZONE_SUCCESS'
export const GET_PRODUCT_REVIEWS_SUCCESS = 'GET_PRODUCT_REVIEWS_SUCCESS'

export const POPULAR_PRODUCTS = ' POPULAR_PRODUCTS'
export const GET_PRODUCTS_BY_ID = 'GET_PRODUCTS_BY_ID'

export const ADD_PRODUCT = 'ADD_PRODUCT'
