export const PRODUCT_ERROR = 'PRODUCT_ERROR'
export const PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST'

export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS'
export const GET_PRODUCT_BY_ID_SUCCESS = 'GET_PRODUCT_BY_ID_SUCCESS'
export const GET_PRODUCTS_BY_CATEGORY_ID = 'GET_PRODUCTS_BY_CATEGORY_ID'
export const GET_PRODUCTS_BY_CATEGORY_NAME = 'GET_PRODUCTS_BY_CATEGORY_NAME'


export const GET_PRODUCTS_BY_PRODUCT_ID = 'GET_PRODUCTS_BY_PRODUCT_ID'
export const GET_PRODUCTS_BY_PRODUCT_NAME = 'GET_PRODUCTS_BY_PRODUCT_NAME'

export const POPULAR_PRODUCTS = ' POPULAR_PRODUCTS'
export const GET_PRODUCTS_BY_ID = 'GET_PRODUCTS_BY_ID'

export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS'
export const CREATE_PRODUCT_REQUEST = 'CREATE_PRODUCT_REQUEST'
export const CREATE_PRODUCT_ERROR = 'CREATE_PRODUCT_ERROR'

export const REMOVE_PRODUCT_SUCCESS = 'REMOVE_PRODUCT_SUCCESS'

export const GET_PRODUCTS_BY_NAME = 'GET_PRODUCTS_BY_NAME'

export const GET_SEARCH_SUCCESS = 'GET_SEARCH_SUCCESS'