export const CLIENT_ERROR = 'CLIENT_ERROR'
export const CLIENT_REQUEST = 'GET_CLIENT_REQUEST'

export const GET_CLIENT_SUCCESS = 'GET_CLIENT_SUCCESS'
export const GET_CLIENT_BY_ID_SUCCESS = 'GET_CLIENT_BY_ID_SUCCESS'
export const GET_CLIENT_REVIEWS_SUCCESS = 'GET_CLIENT_REVIEWS_SUCCESS'

export const ADD_CLIENT = 'ADD_CLIENT'
export const ADD_REVIEW = 'ADD_REVIEW'
