export const USER_ERROR = 'USER_ERROR'
export const USER_REQUEST = 'GET_USER_REQUEST'

export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_BY_ID_SUCCESS = 'GET_USER_BY_ID_SUCCESS'
export const GET_USER_REVIEWS_SUCCESS = 'GET_USER_REVIEWS_SUCCESS'

export const ADD_USER = 'ADD_USER'
export const ADD_REVIEW = 'ADD_REVIEW'
