
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';

export const USER_ERROR = 'USER_ERROR';
export const USER_LOADING = 'USER_LOADING';

//CRUD
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';

export const TOGGLE_USER_ADMIN_SUCCESS = 'TOGGLE_USER_ADMIN_SUCCESS'
