export const WISHLIST_ERROR = 'WISHLIST_ERROR';
export const WISHLIST_REQUEST = 'WISHLIST_REQUEST';


export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST'
export const REMOVE_FROM_WHISHLIST = 'REMOVE_FROM_WHISHLIST'

export const GET_WISHLIST_SUCCESS = 'GET_WISHLIST_SUCCESS'
export const CREATE_WISHLIST_SUCCESS = 'CREATE_WISHLIST_SUCCESS'
export const UPDATE_WISHLIST_SUCCESS = 'UPDATE_WISHLIST_SUCCESS'
export const DELETE_WISHLIST_SUCCESS = 'DELETE_WISHLIST_SUCCESS'