export const WISHLIST_ERROR = 'WISHLIST_ERROR';
export const WISHLIST_LOADING = 'WISHLIST_LOADING';

export const GET_WISHLIST = 'GET_WISHLIST_BY_USER'
export const POST_WISHLIST = 'POST_WISHLIST'
export const UPDATE_WISHLIST = 'UPDATE_WISHLIST'
export const DELETE_WISHLIST = 'DELETE_WISHLIST'