export const HANDY_ERROR = 'HANDY_ERROR'
export const HANDY_REQUEST = 'GET_HANDY_REQUEST'

export const GET_HANDY_SUCCESS = 'GET_HANDY_SUCCESS'
export const GET_HANDY_BY_ID_SUCCESS = 'GET_HANDY_BY_ID_SUCCESS'
export const GET_HANDYS_BY_CATEGORY_ID = 'GET_HANDYS_BY_CATEGORY_ID'
export const GET_HANDYS_BY_CATEGORY_NAME = 'GET_HANDYS_BY_CATEGORY_NAME'

export const GET_HANDY_BY_ZONE_SUCCESS = 'GET_HANDY_BY_ZONE_SUCCESS'
export const GET_HANDY_REVIEWS_SUCCESS = 'GET_HANDY_REVIEWS_SUCCESS'

export const POPULAR_HANDYS = ' POPULAR_HANDYS'
export const GET_HANDYS_BY_ID = 'GET_HANDYS_BY_ID'

export const ADD_HANDY = 'ADD_HANDY'
