export const CATEGORY_ERROR = 'CATEGORY_ERROR'
export const CATEGORY_REQUEST = 'GET_CATEGORY_REQUEST'

export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORY_SUCCESS'
export const GET_CATEGORY_BY_ID_SUCCESS = 'GET_CATEGORY_BY_ID_SUCCESS'

export const ADD_CATEGORY = 'ADD_CATEGORY'
export const SEARCH_CATEGORIES = 'SEARCH_CATEGORY'

export const REMOVE_CATEGORY = 'REMOVE_CATEGORY'
