export const CATEGORY_ERROR = 'CATEGORY_ERROR'
export const CATEGORY_REQUEST = 'GET_CATEGORY_REQUEST'

export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORY_SUCCESS'
export const GET_CATEGORY_BY_ID_SUCCESS = 'GET_CATEGORY_BY_ID_SUCCESS'

// export const ADD_CATEGORY = 'ADD_CATEGORY'
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCESS'
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS'
export const REMOVE_CATEGORY_SUCCESS = 'REMOVE_CATEGORY_SUCCESS'

export const SEARCH_CATEGORIES = 'SEARCH_CATEGORY'


