export const OFFER_ERROR = 'OFFER_ERROR'
export const OFFER_REQUEST = 'GET_OFFER_REQUEST'

export const CREATE_OFFER_SUCCESS = 'CREATE_OFFER_SUCESS'

export const GET_OFFERS_SUCCESS = 'GET_OFFERS_SUCCESS'
export const GET_OFFER_BY_ID_SUCCESS = 'GET_OFFER_BY_ID_SUCCESS'

export const UPDATE_OFFER_SUCCESS = 'UPDATE_OFFER_SUCCESS'
export const REMOVE_OFFER_SUCCESS = 'REMOVE_OFFER_SUCCESS'




