export const ORDER_ERROR = 'ORDER_ERROR';
export const ORDER_LOADING = 'ORDER_LOADING';

export const GET_ORDER_BY_ID_SUCCESS = 'GET_ORDER_BY_ID_SUCCESS'
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDERS_SUCCESS'
export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS';