
export const CREATE_CART = 'CREATE_CART';
export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const DELETE_ITEM_FROM_CART = 'DELETE_ITEM_FROM_CART';
export const CLEAR_CART = 'CLEAR_CART';
export const ERROR_CART = 'ERROR_CART';
export const LOADING_CART = 'LOADING_CART';
export const INCREMENT_QUANTITY = 'INCREMENT_QUANTITY'
export const DECREMENT_QUANTITY = 'DECREMENT_QUANTITY'

