export const BRANCH_ERROR = 'BRANCH_ERROR'
export const BRANCH_REQUEST = 'GET_BRANCH_REQUEST'

export const CREATE_BRANCH_SUCCESS = 'CREATE_BRANCH_SUCESS'

export const GET_BRANCHES_SUCCESS = 'GET_BRANCHES_SUCCESS'
export const GET_BRANCH_BY_ID_SUCCESS = 'GET_BRANCH_BY_ID_SUCCESS'

export const UPDATE_BRANCH_SUCCESS = 'UPDATE_BRANCH_SUCCESS'
export const REMOVE_BRANCH_SUCCESS = 'REMOVE_BRANCH_SUCCESS'

export const SEARCH_CATEGORIES = 'SEARCH_BRANCH'


